---
title: "Juvenile vs Adult"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,error = FALSE,message = FALSE,fig.pos="h")
library(tidyverse)
library(limma)
source("R/utils.R")
```

## Juvenile vs Adult


```{r, data_prep}

mq_data <- load_mq_annotated()
sample_data <- readxl::read_excel("raw_data/maxquant/sample_data.xlsx")

mq_data_lfq_norm <- lognorm_lfq(mq_data) %>% 
  select(prot_id,matches('LFQ.*[1-3]P[1-3]|LFQ.*_S[1-3][AB]')) %>% 
  gather(sample_code,LFQ,-prot_id) %>% 
  mutate(sample_code = extract_sample_codes(sample_code)) %>% 
  left_join(sample_data,by="sample_code") %>% 
  group_by(prot_id,individual) %>% 
  summarise(sample_code = first(sample_code),LFQ=mean(LFQ,na.rm=TRUE)) %>% 
  ungroup() %>% 
  select(-individual) %>% 
  spread(sample_code,LFQ) %>% 
  column_to_rownames("prot_id") %>% 
  as.matrix()

model_data <- readxl::read_excel("raw_data/maxquant/sample_data.xlsx") %>% 
  filter(sample_code %in% colnames(mq_data_lfq_norm)) %>% arrange(sample_order)


all(model_data$sample_code == colnames(mq_data_lfq_norm))
```

Comparing Juv vs Adult is tricky because they were done on different mass spectrometers.  Nevertheless if we believe that these instruments are sufficiently similar we can compare them.  We find many (639) proteins different at the 5% FDR level.

```{r juv_vs_adult}
design_ja <- model.matrix(~sample_type, model_data)

fit_ja <- lmFit(mq_data_lfq_norm,design_ja)
bfit_ja <- eBayes(fit_ja)

tt_ja <- topTable(bfit_ja,n = Inf,p.value = 0.05, coef = "sample_typeJuvenile PSG")
volcanoplot(bfit_ja,coef = "sample_typeJuvenile PSG")
```


```{r by_tissue}
design <- model.matrix(~tissue, model_data)

fit <- lmFit(mq_data_lfq_norm,design)
bfit <- eBayes(fit)

# tt <- topTable(bfit,n = Inf, coef = "sample_typeJuveline PSG")
# volcanoplot(bfit,coef = "sample_typeJuveline PSG")

# Anova across developmental stages
#
tt <- topTable(bfit,n = Inf, coef = 2:4)

tt_anno <- tt %>% rownames_to_column("prot_id") %>% 
  left_join(lognorm_lfq(mq_data), by="prot_id") %>% 
  select(starts_with("tissue"),AveExpr,adj.P.Val,Description,prot_id,Kegg,starts_with("gene_ontology")) %>% 
  filter(adj.P.Val<0.01) %>% 
  column_to_rownames("prot_id") %>% 
  as.data.frame()

tt_hm_matrix <- tt_anno %>% 
  select(starts_with("tissue")) %>% 
  as.matrix()

pheatmap(tt_hm_matrix, show_rownames = FALSE)

```


