---
title: "temp_tree_abstract"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggtree)
library(ape)
library(phangorn)
#source("https://bioconductor.org/biocLite.R")
#biocLite("ggtree")
#biocLite("preprocessCore")
source("R/utils.R")
```



```{r, prepare_data}
tree <-  read.tree("raw_data/serine_proteases/sp1_200_molluscs_v2.fasta.contree")
tip_data <- serine_protease_treedata()

tree$tip.label <- tree$tip.label %>% str_replace_all(pattern = "_-_PF00089", replacement = "")
```

First plot a large tree with all species

```{r}
rtree <- midpoint(tree)

tip_data$Order <- factor(tip_data$Order,levels = c("Octopus","Cuttlefish","Squid","Gastropod","Bivalve"))

sp_tree_plot <- ggtree(rtree,size=0.1) %<+% tip_data +  geom_tiplab(aes(label=simple_label,color=Order),size=1) +
  geom_text2(aes(subset = !isTip, label=label), hjust=1.2, vjust = -0.5, size=1) + # Uncomment to show node labels. This tell us that node 337 is what we want for the detailed tree
#  geom_text2(aes(subset = !isTip, label=node), hjust=1.2, vjust = -0.5, size=1) + 
    geom_treescale(offset = -2) + 
  theme(legend.position=c(0.8,0.7), legend.text = element_text(size=7,face = "italic"), legend.title = element_blank(),
        legend.key.size = unit(2,"mm")) +
  xlim(0,3.30) + 
  #scale_color_manual(values=  c("Octopus"="#FF7E79","Cuttlefish"="#FF9300","Squid"="#FFD479","Gastropod"="#0096FF","Bivalve"="#942193")) +
                                      guides(color = guide_legend(override.aes = list(size = 3)))


#ggsave(sp_tree_plot,filename = "figures/serine_proteases_tree.png", width = 17.8, height = 20, units = "cm")
```

```{r}

sp_nodes <- ggtree(rtree,size=0.1) %<+% tip_data +  geom_tiplab(aes(label=simple_label,color=Order),size=1) + geom_text2(aes(subset = !isTip, label=node), hjust=1.2, vjust = -0.5, size=1) + geom_treescale(offset = -2) +
 theme(legend.position=c(0.8,0.7), legend.text = element_text(size=7,face = "italic"), legend.title = element_blank(),legend.key.size = unit(2,"mm")) +
xlim(0,3.30) +
guides(color = guide_legend(override.aes = list(size = 3)))


to_collapse <- ggtree(rtree,size=0.1) %<+% tip_data +  geom_tiplab(aes(label=simple_label,color=Order),size=1) + geom_treescale(fontsize=1, linesize = 0.1) +
  geom_text2(aes(subset = !isTip, label=label), hjust=1.2, vjust = -0.5, size=1) + 
  theme(legend.position=c(0.8,0.7), legend.text = element_text(size=7,face = "italic"), legend.title = element_blank(),
        legend.key.size = unit(2,"mm")) +
  xlim(0,1) + guides(color = guide_legend(override.aes = list(size = 3)))

#ggsave(sp_nodes,filename = "tmp_nod.png", width = 17.8, height = 20, units = "cm")

# tp1 <- collapse(to_collapse,336) 
# tp2 <- collapse(tp1, 504) 
# tp3 <- collapse(tp2, 338)  + theme(legend.position="none") + xlim(0,0.5)
# 
# ggsave(tp3, filename = "figures/tree_collapsed_unlabelled.png", width = 4, height = 4, units = "cm" )


t1 <- collapse(to_collapse,337) + 
  geom_point2(aes(subset=(node == 337)), size=5, shape=23, fill="steelblue") +
  geom_text2(aes(subset=(node == 337)), label="Molluscs", size = 1, hjust=-0.2) 

t2 <- collapse(t1, 504) + 
  geom_point2(aes(subset=(node == 504)), size=0.03, shape=21, fill="chartreuse3") +
  geom_text2(aes(subset=(node == 504)), label="Gastropod and Octopods",size = 1, hjust=-0.2)

tree_collapsed <- collapse(t2, 335) + 
  geom_point2(aes(subset=(node == 335)), size=3, shape=21, fill="coral") +
  geom_text2(aes(subset=(node == 335)), label="Cephalopods", size = 1, hjust=-0.2) +         theme(legend.position="none") + xlim(0,0.5)

ggsave(tree_collapsed, filename = "figures/tree_collapsed.png", width = 4, height = 4, units = "cm" )
```

Plot the big tree unrooted 

```{r}
sp_unrooted <- ggtree(tree,size=0.1, layout="unrooted") %<+% tip_data + 
#  geom_tiplab(aes(label=simple_label,color=Order),size=1) + 
  geom_text2(aes(subset = (!isTip & label>90), label=label), hjust=1.2, vjust = -0.5, size=1) + 
  geom_tippoint(aes(color=Order)) +
  geom_hilight_encircle(node=337) +
  scale_color_manual(values=  c("Octopus"="#FFB7B7","Cuttlefish"="#FF7474","Squid"="#FF0001","Gastropod"="#5DB330","Bivalve"="#3283EA")) +
  theme(legend.position=c(0.8,0.2), legend.text = element_text(size=7,face = "italic"), legend.title = element_blank(),legend.key.size = unit(2,"mm")) +
  guides(color = guide_legend(override.aes = list(size = 3)))


ggsave(sp_unrooted,filename = "figures/serine_proteases_unrooted_tree.png", width = 17.8, height = 20, units = "cm")
```


Plot big tree unrooted in simplified form suitable for graphical abstract

```{r}
tip_data_simplified <- tip_data %>% 
  mutate(Class = ifelse( Order %in% c("Octopus", "Cuttlefish", "Squid"), "Cephalopod", as.character(Order))  ) 

sp_unrooted_simple <- ggtree(tree,size=0.1, layout="unrooted") %<+% tip_data_simplified + 
  geom_tippoint(aes(color=Class),size=0.5) +
#  geom_hilight_encircle(node=337) +
  scale_color_manual(values=  c("Cephalopod"="#FF0001","Gastropod"="#5DB330","Bivalve"="#3283EA")) +
  theme(legend.position=c(0.8,0.1),legend.background = element_rect(fill="transparent"), legend.text = element_text(size=6, family = "Helvetica"), legend.title = element_blank(),legend.key.size = unit(2,"mm")) 

#+  guides(color = guide_legend(override.aes = list(size = 3)))

ggsave(sp_unrooted_simple,filename = "figures/serine_proteases_unrooted_tree_toc.pdf", width = 5, height = 5, units = "cm")
```

```{r}
unrooted_node_tree <- ggtree(tree,size=0.1, layout="unrooted") %<+% tip_data + geom_tiplab(aes(label=simple_label,color=Order),size=1) + geom_text2(aes(subset = !isTip, label=node), hjust=1.2, vjust = -0.5, size=1) + theme(legend.position=c(0.8,0.2), legend.text = element_text(size=7,face = "italic"), legend.title = element_blank(),legend.key.size = unit(2,"mm")) + guides(color = guide_legend(override.aes = list(size = 3)))

#ggsave(unrooted_node_tree,filename = "tmp_unrooted_node.png", width = 17.8, height = 20, units = "cm")


u1 <- collapse(unrooted_node_tree, 336) +
  geom_point2(aes(subset=(node == 336)), size=5, shape=23, fill="steelblue") +
  geom_text2(aes(subset=(node == 336)), label="Molluscs", size = 1, hjust=-0.2)

collapse(u1, 338) +
  geom_point2(aes(subset=(node == 337)), size=3, shape=21, fill="coral") +
  geom_text2(aes(subset=(node == 337)), label="Cephalopods", size = 1, hjust=-0.2) +         theme(legend.position="none")
```

